apiVersion: v1
kind: Service
metadata:
  name: music-site-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: music-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
