apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-site
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: music-site
  template:
    metadata:
      labels:
        app: music-site
    spec:
      containers:
        - name: music-site
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: static-images
              mountPath: /app/static/images
      volumes:
        - name: static-images
          emptyDir: {}
