apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_URI: mongodb://mongodb-service:27017/artist_db
  FLASK_ENV: production
  SECRET_KEY: {{ .Values.app.secretKey }}
