namespace: music-site
mongodb:
  image:
<<<<<<< HEAD
    repository: mongo
    tag: "1.0.26"
=======
    repository: mongo # Use the official MongoDB image
    tag: "1.0.26"
>>>>>>> d92cf9340428769e3043ebbd25728cbf3c0befbb
  replicas: 1
  storage:
    size: 5Gi
app:
  image:
<<<<<<< HEAD
    repository: cheffen/music-site
    tag: "1.0.26"
=======
    repository: cheffen/music-site # Your application image repository
    tag: "1.0.26"
>>>>>>> d92cf9340428769e3043ebbd25728cbf3c0befbb
  replicas: 2
  secretKey: your_secure_secret_key  
