namespace: music-site

mongodb:
  image:
    repository: mongo
    tag: "1.0.42"
  replicas: 1
  storage:
    size: "5Gi"

app:
  image:
    repository: cheffen/music-site
    tag: "1.0.42"
  replicas: 2
  secretKey: "your_secure_secret_key"
