namespace: music-site
mongodb:
  image:
    repository: mongo # Use the official MongoDB image
    tag: "1.0.20"
  replicas: 1
  storage:
    size: 5Gi
app:
  image:
    repository: cheffen/music-site # Your application image repository
    tag: "1.0.20"
  replicas: 2
  secretKey: your_secure_secret_key 