namespace: music-site

mongodb:
  image:
    repository: mongo
    tag: "6.0" # Remains unchanged
  replicas: 1
  storage:
    size: "5Gi"

app:
  image:
    repository: cheffen/music-site
    tag: "1.0.14" # Updated to the new IMAGE_TAG
  replicas: 2
  secretKey: "your_secure_secret_key"
